apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: grafana
    helm:
      values: |
        adminUser: admin
        adminPassword: aspenmesh
        dashboards:
          default:
            kubernetes-cluster:
              gnetId: 7249
              revision: 1
              datasource: Prometheus
            kubernetes-cluster-monitoring-prometheus:
              gnetId: 1621
              datasource: Prometheus
            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Prometheus
            istio-mesh:
              gnetId: 7639
              revision: 92
              datasource: Prometheus
            istio-service:
              gnetId: 7636
              revision: 92
              datasource: Prometheus
            istio-workload:
              gnetId: 7630
              revision: 92
              datasource: Prometheus
            istio-performance:
              gnetId: 11829
              revision: 92
              datasource: Prometheus
            istio-controlplane:
              gnetId: 7645
              revision: 92
              datasource: Prometheus
            istio-loki:
              gnetId: 14876
              revision: 2
              datasource: Loki
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: default
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: false
                options:
                  path: /var/lib/grafana/dashboards/default
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                url: http://loki.istio-system.svc.cluster.local:3100
                access: proxy
                jsonData:
                  derivedFields:
                    - datasourceName: Tempo
                      matcherRegex: "traceID=(\\w+)"
                      name: TraceID
                      url: "$${__value.raw}"
                      datasourceUid: tempo
              - name: Prometheus
                type: prometheus
                url: http://prometheus.istio-system.svc.cluster.local:80
                access: proxy
                isDefault: true
              - name: Tempo
                type: tempo
                access: proxy
                url: http://tempo.istio-system.svc:3100
        persistence:
          enabled: true
        service:
          loadBalancerIP: "10.1.1.55"
          type: LoadBalancer
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.13
  syncPolicy:
    automated:
      prune: true
      selfHeal: true