apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: grafana
    helm:
      values: |
        adminUser: admin
        adminPassword: admin
        dashboards:
          default:
            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Prometheus
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus.istio-system.svc.cluster.local:80
                access: proxy
                isDefault: true
        persistence:
          enabled: true
        service:
          loadBalancerIP: "10.1.1.55"
          type: LoadBalancer
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.11
  syncPolicy:
    automated:
      prune: true
      selfHeal: true