apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-multicluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: helloworld
  project: default
  source:
    path: clusters/cluster1/multicluster
    repoURL: git@gogs.aspendemo.org:aspenmesh/helloworld.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
