apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    path: clusters/cluster1/istio-system
    repoURL: git@gogs.aspendemo.org:aspenmesh/istio.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
