apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: kiali-operator
    helm:
      values: |
        cr:
          create: true
          namespace: istio-system
          spec:
            auth:
              strategy: anonymous
            deployment:
              service_type: LoadBalancer
              additional_service_yaml: { "loadBalancerIP": "10.1.1.53" }
            external_services:
              istio:
                component_status:
                  components:
                  - app_label: istiod
                    is_core: true
                    is_proxy: false
                  - app_label: istio-ingressgateway
                    is_core: true
                    is_proxy: true
                  - app_label: istio-eastwestgateway
                    is_core: false
                    is_proxy: true
                  - app_label: istio-egressgateway
                    is_core: false
                    is_proxy: true
              grafana:
                auth:
                  password: aspenmesh
                  username: admin
                in_cluster_url: "http://grafana.istio-system.svc.cluster.local:80"
                url: "http://grafana.cluster1.aspendemo.org"
              prometheus:
                url: "http://prometheus.istio-system.svc.cluster.local:80"
              tracing:
                in_cluster_url: "http://jaeger-collector.istio-system:14250"
                url: "http://jaeger.cluster1.aspendemo.org"
                whitelist_istio_system: ["jaeger-query", "istio-ingressgateway", "istio-eastwestgateway", "istio-egressgateway"]
    repoURL: https://kiali.org/helm-charts
    targetRevision: v1.41.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
