apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: loki
    helm:
      values: |
        adminUser: admin
        adminPassword: admin
        persistence:
          enabled: true
        service:
          loadBalancerIP: "10.1.1.56"
          type: LoadBalancer
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true