apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
        server:
          fullnameOverride: prometheus
          service:
            loadBalancerIP: "10.1.1.54"
            type: LoadBalancer
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 14.9.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true