apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: promtail
    helm:
      values: |
        config:
          lokiAddress: http://loki:3100/loki/api/v1/push
          snippets:
            extraScrapeConfigs: |
              # Add an additional scrape config for syslog
              - job_name: journal
                journal:
                  path: /var/log/journal
                  max_age: 12h
                  labels:
                    job: systemd-journal
                relabel_configs:
                  - source_labels:
                      - '__journal__systemd_unit'
                    target_label: 'unit'
                  - source_labels:
                      - '__journal__hostname'
                    target_label: 'hostname'
        extraVolumes:
          - name: journal
            hostPath:
              path: /var/log/journal
        extraVolumeMounts:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.8.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true