apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: cluster2
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-cluster2
  namespace: istio-system
stringData:
  cluster2: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1UQXhNVEU0TWpVME5sb1hEVE14TVRBd09URTRNalUwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEtEClVVMGg3cjhzVVZydlk5a2pzSUVSOUVZNFZlYmtmdVlaMjBGaWpiOGlEMDJSazhCc1ErazBTNzhyYzdnT2RncHYKMUMrUGtkWGt0dG5PTHdua24yYk9nZnFQSGk1YWlFazlGYVFoUWJDTGdlWS9IVVJrRmxZT0hWY2w0TUNCMjhRTgpuajlBWjl0dVdyelA2T0dJWXVYTVpFejlNU1VmbG9TaTd2ZWo4VWpGZlE3YjhqNWswZTIzNnk3WFJCNlIxejAzCk5aZVVFSjZ4TU5ESXFpY3paR3htb1JwVmpSWnhzQUZRdXpiZmFnMGlHWkNLb05SN0dLRHNmZWs0eWtrZm9HaEMKZXlxL1hKWVZKRHk5VSt3K3hxNStzRlVqSjZBQkp5T0tVWG1XdVBPYThEUXMrbEZ1TEtOejZidzg3d2F0NVlSWQpTelZMS09IQkRPR1JuT0xoWVFrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLOTE4WS9STnlMeDZId3l1em5scHpQNWs5cmNNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDWFU4ckJScnkrazhaT1c3UnVqWGhUOTVuOFlnMlN1Z1lNdnBQcjVxM3U3OWQ4dXJCRApoTWlYckRPNW4rQmZEQ0QzZG8wSS9jdHVXTWFPQWc2dWNkbGZ2WUN5UTlnT3pKMm1Fb2k1TXRHYjgvaEZTOG1PClIvMTVHQll0emtMNDV2Mll2b1haY3JpNkxyT2xLSzMyYXgxZXlVY2NZNGhBbjRBeVFSMXVKSlpzaVNZbndFdHgKWm5SR0VwWStMNmlGLzRqNk9OYnNnTE9VeldBVEIrVjJWOWEwczRGa01wOXpSQlN1Q2tVaUluT0VKTHVzWEYrbQpJd1NXblFLbFVIZ3ZOSlNMOUtvTmhtSzRGeHpNODl6TC9oRmk1aVJZUmlKUkptejd2cjFybkQrcXhnTm9MeW15CmNIdTFCdnJsSmpwMlVCcmFOSlhJOXhqVDdmekpJQ1pyT3luSwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://10.1.1.8:6443
      name: cluster2
    contexts:
    - context:
        cluster: cluster2
        user: cluster2
      name: cluster2
    current-context: cluster2
    kind: Config
    preferences: {}
    users:
    - name: cluster2
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6Inp0cThOTV9MUlhmdnBOVVQ5dFpNcTFWc0tQN2ZDNUZZcFlkeGczVUdMQ3cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8tcmVhZGVyLXNlcnZpY2UtYWNjb3VudC10b2tlbi1razU3eiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJpc3Rpby1yZWFkZXItc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzM5MTFkMTQtYzRiZS00MjVmLTg4MDItZWUxMzg1MDJjOTk5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlzdGlvLXN5c3RlbTppc3Rpby1yZWFkZXItc2VydmljZS1hY2NvdW50In0.CJ8L1SXNampGowCF4IGRn0HpyWcUhEufVTaaWUKTAe1U5ccr6GtlGXMMbredIvFAUDeg414iKhD4_9Mx8Ue_JxNCIq94c0aIr_n4e3L4XVkFZDBch8MbX6H3AtHtVrcET4UdINyb5ie02tVhlS3EnnPNPZalZPRCQlkDkZb1xdG0DQoyIzgkMpGV8-zWK3epxKLsix2GyFjif6V5sg5BK9xtKWqBznZ-vH7z6klOflC9L0c28k-PUr_UNXmXWz_1OwnZmOT6MsS-t2x4ybh1rVjWg24zci9Dqo4I2xx0wmfjgtF4E3YFkmJjzbTWWlfSCmUNoMX2DKoQBF8FLpaKLg