apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: cluster2
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-cluster2
  namespace: istio-system
stringData:
  cluster2: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1UQXdOakUwTkRVMU9Gb1hEVE14TVRBd05ERTBORFUxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXJICmdJMnUwcFdzK0lBL1dZYTU1NFJLdjFTaHFQNktMODc3cGtackJYcmVFSVpESzByd282TWJRbkNYUi9Na0h6WGcKMjdDS1pnczNZZE1xUTlMUHIyYU5XalZFd0JORytyNkpyTkFsMFA3L0FQYmErMDRhZG5ZZTlCT0k5NVQzVW1VYQp3Y3hYdDZLS1Z2SUFPQklqQnp1d3YvQitHMlR6cWV6YUpzYmhUVk94eWN2MlJRa09NeXBoQzdXWjZodU03bjhJCkliYXAxZUIxQkJ3bmJiSFdHV3h6a3RDOXpPUXhPc2h2TGhOZDBvK2NOdWl3T3ZKc0wzUmNlS2hPNGYwZlpLYkkKYjFMWEZ3VW1ZMWxCdHc1RHRiZUtPYmwrbzdvYnFuZ3grM1VjOTBZZVhBZHF6UlRXQUJoVXI4SnZwRnR2WUVQVwppeDNtcG1PVDl0S3l2VHRSQlhzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEMXVieElMM2ZwSWVZYzh4SlNpU1o4YlZFdDhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBeityQzdtRzVqVnJvK0l4VW9laUpUNFNwYXo5RGJUNVE3YmQ5T1pjUS8zRDJEbDluegp4YzdZNXVsRkxPQ3UvM0UwSGV0SzV1V2orY1UvcWUza0VuUnNnbi9UY2o1M3F0WllOSm82MnY3MUtybXlIbmxkCndDaUtHSzhhNjRUSE13d0taU0xCbnlpcDFGcjFYSEJWYXZFRjd5UUlINktMZ1g0OTZaT2lJZkl1Q3B3eXB4b04KQjQ3U1hoOTdJdm5tUFY5MjU5aGk5WjN0ZExXQWQ3VzRPWC95OGpRZjhiUnQ3VDQrdkZsd0Y1N3VUZ1U1OXgwSQphQWl0b3gxYlQ0SkhReCtSSFNFNDV6WlBaTGNiaTVLYU1IQVJHZ0hPRG94YVEzVlNwWTcwTE5YeE1rNnp2QTJwClhOU2RWRUdxM3RNRUJiajE5L2FtaFFSZ1dwWDMzU2VOYkhMaQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://10.1.1.8:6443
      name: cluster2
    contexts:
    - context:
        cluster: cluster2
        user: cluster2
      name: cluster2
    current-context: cluster2
    kind: Config
    preferences: {}
    users:
    - name: cluster2
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il8tRUpMbmkzMzJzbFpwbVNHaXd4TnJ0cFQwRzBUekVFaExSWHhxa25kSTAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8tcmVhZGVyLXNlcnZpY2UtYWNjb3VudC10b2tlbi1ybWJ6ZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJpc3Rpby1yZWFkZXItc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZmU1Y2U0NTgtNTRiYS00NDRmLTliOTYtYTc2MDAxM2EzMDY0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlzdGlvLXN5c3RlbTppc3Rpby1yZWFkZXItc2VydmljZS1hY2NvdW50In0.yrhl2EN6VXFu_ZrpM3qkg3qEGHNYSfv8RUCTqlptDRykhd_QGEd5p2bz5JBXJ8kMlTvaBS8m_9kewuFnDdv36vzOeX79VOmNsGsfPVqd6soatCcWvIkq65t2kE8es-m682UUbbCH7fCeGDVg1BpvqS0np0j7EQQ5noLgCuWAgkYc_ghK0UfgJWJyxHBfqofRwLZYeU0TfK8Ueud2YQM4pCbdvd_4RtKVJUxPqUmBmmPCO8ve9_ZWJlpzFcroSv6-POyPEORP3Ppz8XX9g2wSAoHSHKrhkZipzeZyHSmLQADDMtQeKWcEFM3fJe-iBKi5kGagpc3rdfSz4EOGINf_OA
