apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: jaeger-operator
    helm:
      values: |
        jaeger:
          create: true
          namespace: istio-system
          spec:
            strategy: allInOne
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.25.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true