apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: cluster1
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-cluster1
  namespace: istio-system
stringData:
  cluster1: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1UQXdOakUwTkRVMU4xb1hEVE14TVRBd05ERTBORFUxTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHc4CmZKUGJoMmVTRHdybjlIT0ZEOHBGWVo4S0s4YzNYN1FUQlQvWjUzTUJCakFJRnBubG9ndXVqcnpJZXJUNUF1TmUKd1cydTlKSXNpSTZlQXJVYlh1dDJXMllZUXNkV21tb1Jkb1pMUWl6WEkxKzErK3JiK25mQVh5YzJ6K2RLVnE0NwpPRTNMNTdPUHlqZG1IMnRnVWlkUmY1OVJPUGJLRTFRWml1YWljWmNRcG1EcVlPOWhMQzV3dHc3N2gzSlBDQXFhClNFQko5NjBMbVVGbUVQbzhWOTl4Rk80V0Q4Z3IyZEkwSng5cEE1RnFGMFFKS2ZXK1BSK2lvZnFNS0F1Q1NabUMKMGRsM3ovQ3BVWUFIWVBUQUlWd2NYZEt1bDFMYjIzeVdZd1E1eGc1andDRktJV0JzVThLTnhrNjJDRGJ1TjViVworU3ZNNDF2ZGxhNmdybHNhU2VNQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNZmhmcUhMcWhSWGViczF5RFBGMThlOFVwN1BNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCamtLMVdrVXNIWktSVFZIYVFPQi93N1Z2bE9Rd3o1QVNJYkVEbzIzcVZ6NDZTSGxaSgpiZXdpc21yVVBsR3U2cGIyM0l6Slg0V1QyZ0FpdGJIQWRCbEgwV2xCczdsd2ZYTmt6UWwyU04yMkpkOEtmNG9PClA5MUFYQzdmMkluRFlZS3czeFpVcXVPZ1Jua1AremlQclNNRlFMaHB5amg0Q1hQcEh6Z3ZqMkFPZlJXdUdscmYKMldnNXk3TlZ4cm1qdndlUnJLanNWMWFCOEdRT1pOVGxJTVdlUnJ4anM4NnVsaXozV0ZlWWx4dmZEcTZFaStxeApPQmc2bXZNRG5wUFNMRmNScU14QnRwWFdMTWI3ZDBreVZyejVxc0tiNS93WENVTWR0N2JpTWZ2Vlc2Z1pkTWNDCkVnbzZ3Ymw5RkRjcmhDMHd1S2tEdll3U0dxVHpUL0Q1SWNEQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://10.1.1.5:6443
      name: cluster1
    contexts:
    - context:
        cluster: cluster1
        user: cluster1
      name: cluster1
    current-context: cluster1
    kind: Config
    preferences: {}
    users:
    - name: cluster1
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6InR3eDF1RDNHcnFFZ1RvS1NNY1Bkc1FTcmJSMXc0SWYxd1ItdXM4aXdRdzAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8tcmVhZGVyLXNlcnZpY2UtYWNjb3VudC10b2tlbi1mN3c4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJpc3Rpby1yZWFkZXItc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMmNlNjM1MjQtYTA0NC00ZGVjLWExN2MtMjFlODk4NzRmMjFmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlzdGlvLXN5c3RlbTppc3Rpby1yZWFkZXItc2VydmljZS1hY2NvdW50In0.NA5-aaXKlyQNRa6OPg3qn8-7GYA24_iDahqLkMKXK_D_uKZlxhjMjCtnz3WM5AGuYMOVbWIVVy-I4HpDlfGk4sHc-WOVa-2k1hIk24vounAnekQI6MEdVNiQF5pWlL0a8_7AdeuUrgs4MICUUNPdoteo1ARDYlBSmLxnpDIW-NuHvMmv_Sxiea_DrurYdZGhT2YM3l1jJWR8NIBKzOn5GTn7EcehwtIPT8TBB3f1FHteDgorKUbDn4FNWnZo_E_ZVSQh7_Cv-_Bes8cWhWJPY9Kypt8B3Mmgml-_K1vrM6CwLsdL0sD-3e4rJS18bHngdpNj20QHaj45hjUDDVkOPw
